// Generated by gencpp from file iau_ros_msgs/ChangeLane.msg
// DO NOT EDIT!


#ifndef IAU_ROS_MSGS_MESSAGE_CHANGELANE_H
#define IAU_ROS_MSGS_MESSAGE_CHANGELANE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace iau_ros_msgs
{
template <class ContainerAllocator>
struct ChangeLane_
{
  typedef ChangeLane_<ContainerAllocator> Type;

  ChangeLane_()
    : timestamp()
    , change_signal(0)  {
    }
  ChangeLane_(const ContainerAllocator& _alloc)
    : timestamp()
    , change_signal(0)  {
  (void)_alloc;
    }



   typedef ros::Time _timestamp_type;
  _timestamp_type timestamp;

   typedef int32_t _change_signal_type;
  _change_signal_type change_signal;





  typedef boost::shared_ptr< ::iau_ros_msgs::ChangeLane_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::iau_ros_msgs::ChangeLane_<ContainerAllocator> const> ConstPtr;

}; // struct ChangeLane_

typedef ::iau_ros_msgs::ChangeLane_<std::allocator<void> > ChangeLane;

typedef boost::shared_ptr< ::iau_ros_msgs::ChangeLane > ChangeLanePtr;
typedef boost::shared_ptr< ::iau_ros_msgs::ChangeLane const> ChangeLaneConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::iau_ros_msgs::ChangeLane_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::iau_ros_msgs::ChangeLane_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace iau_ros_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'iau_ros_msgs': ['/home/z/iau_ws/src/iau_ros_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::iau_ros_msgs::ChangeLane_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::iau_ros_msgs::ChangeLane_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::iau_ros_msgs::ChangeLane_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::iau_ros_msgs::ChangeLane_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iau_ros_msgs::ChangeLane_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iau_ros_msgs::ChangeLane_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::iau_ros_msgs::ChangeLane_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e2c456b41c05f78bf99ac372ba82fbd5";
  }

  static const char* value(const ::iau_ros_msgs::ChangeLane_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe2c456b41c05f78bULL;
  static const uint64_t static_value2 = 0xf99ac372ba82fbd5ULL;
};

template<class ContainerAllocator>
struct DataType< ::iau_ros_msgs::ChangeLane_<ContainerAllocator> >
{
  static const char* value()
  {
    return "iau_ros_msgs/ChangeLane";
  }

  static const char* value(const ::iau_ros_msgs::ChangeLane_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::iau_ros_msgs::ChangeLane_<ContainerAllocator> >
{
  static const char* value()
  {
    return "time     timestamp\n\
int32    change_signal # 1:left 2:right\n\
";
  }

  static const char* value(const ::iau_ros_msgs::ChangeLane_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::iau_ros_msgs::ChangeLane_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.timestamp);
      stream.next(m.change_signal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ChangeLane_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::iau_ros_msgs::ChangeLane_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::iau_ros_msgs::ChangeLane_<ContainerAllocator>& v)
  {
    s << indent << "timestamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.timestamp);
    s << indent << "change_signal: ";
    Printer<int32_t>::stream(s, indent + "  ", v.change_signal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IAU_ROS_MSGS_MESSAGE_CHANGELANE_H
