// Generated by gencpp from file lidar_perception/cloud_index.msg
// DO NOT EDIT!


#ifndef LIDAR_PERCEPTION_MESSAGE_CLOUD_INDEX_H
#define LIDAR_PERCEPTION_MESSAGE_CLOUD_INDEX_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lidar_perception
{
template <class ContainerAllocator>
struct cloud_index_
{
  typedef cloud_index_<ContainerAllocator> Type;

  cloud_index_()
    : row(0)
    , col(0)  {
    }
  cloud_index_(const ContainerAllocator& _alloc)
    : row(0)
    , col(0)  {
  (void)_alloc;
    }



   typedef uint16_t _row_type;
  _row_type row;

   typedef uint16_t _col_type;
  _col_type col;





  typedef boost::shared_ptr< ::lidar_perception::cloud_index_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lidar_perception::cloud_index_<ContainerAllocator> const> ConstPtr;

}; // struct cloud_index_

typedef ::lidar_perception::cloud_index_<std::allocator<void> > cloud_index;

typedef boost::shared_ptr< ::lidar_perception::cloud_index > cloud_indexPtr;
typedef boost::shared_ptr< ::lidar_perception::cloud_index const> cloud_indexConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lidar_perception::cloud_index_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lidar_perception::cloud_index_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace lidar_perception

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'lidar_perception': ['/home/jydragon/catkin_ws/src/lidar_perception/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::lidar_perception::cloud_index_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lidar_perception::cloud_index_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lidar_perception::cloud_index_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lidar_perception::cloud_index_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lidar_perception::cloud_index_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lidar_perception::cloud_index_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lidar_perception::cloud_index_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e295345dfa8b9e0e80cacb5c0eee8f90";
  }

  static const char* value(const ::lidar_perception::cloud_index_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe295345dfa8b9e0eULL;
  static const uint64_t static_value2 = 0x80cacb5c0eee8f90ULL;
};

template<class ContainerAllocator>
struct DataType< ::lidar_perception::cloud_index_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lidar_perception/cloud_index";
  }

  static const char* value(const ::lidar_perception::cloud_index_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lidar_perception::cloud_index_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16 row\n\
uint16 col\n\
";
  }

  static const char* value(const ::lidar_perception::cloud_index_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lidar_perception::cloud_index_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.row);
      stream.next(m.col);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct cloud_index_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lidar_perception::cloud_index_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lidar_perception::cloud_index_<ContainerAllocator>& v)
  {
    s << indent << "row: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.row);
    s << indent << "col: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.col);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LIDAR_PERCEPTION_MESSAGE_CLOUD_INDEX_H
