// Generated by gencpp from file lidar_perception/grid_index.msg
// DO NOT EDIT!


#ifndef LIDAR_PERCEPTION_MESSAGE_GRID_INDEX_H
#define LIDAR_PERCEPTION_MESSAGE_GRID_INDEX_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lidar_perception
{
template <class ContainerAllocator>
struct grid_index_
{
  typedef grid_index_<ContainerAllocator> Type;

  grid_index_()
    : row(0)
    , col(0)
    , index_cloudID()  {
    }
  grid_index_(const ContainerAllocator& _alloc)
    : row(0)
    , col(0)
    , index_cloudID(_alloc)  {
  (void)_alloc;
    }



   typedef uint16_t _row_type;
  _row_type row;

   typedef uint16_t _col_type;
  _col_type col;

   typedef std::vector<uint32_t, typename ContainerAllocator::template rebind<uint32_t>::other >  _index_cloudID_type;
  _index_cloudID_type index_cloudID;





  typedef boost::shared_ptr< ::lidar_perception::grid_index_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lidar_perception::grid_index_<ContainerAllocator> const> ConstPtr;

}; // struct grid_index_

typedef ::lidar_perception::grid_index_<std::allocator<void> > grid_index;

typedef boost::shared_ptr< ::lidar_perception::grid_index > grid_indexPtr;
typedef boost::shared_ptr< ::lidar_perception::grid_index const> grid_indexConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lidar_perception::grid_index_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lidar_perception::grid_index_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace lidar_perception

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'lidar_perception': ['/home/jydragon/catkin_ws/src/lidar_perception/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::lidar_perception::grid_index_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lidar_perception::grid_index_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lidar_perception::grid_index_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lidar_perception::grid_index_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lidar_perception::grid_index_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lidar_perception::grid_index_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lidar_perception::grid_index_<ContainerAllocator> >
{
  static const char* value()
  {
    return "42a9f2d91187de1c02ab3d7435ded91f";
  }

  static const char* value(const ::lidar_perception::grid_index_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x42a9f2d91187de1cULL;
  static const uint64_t static_value2 = 0x02ab3d7435ded91fULL;
};

template<class ContainerAllocator>
struct DataType< ::lidar_perception::grid_index_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lidar_perception/grid_index";
  }

  static const char* value(const ::lidar_perception::grid_index_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lidar_perception::grid_index_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16 row\n\
uint16 col\n\
uint32[] index_cloudID\n\
";
  }

  static const char* value(const ::lidar_perception::grid_index_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lidar_perception::grid_index_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.row);
      stream.next(m.col);
      stream.next(m.index_cloudID);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct grid_index_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lidar_perception::grid_index_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lidar_perception::grid_index_<ContainerAllocator>& v)
  {
    s << indent << "row: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.row);
    s << indent << "col: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.col);
    s << indent << "index_cloudID[]" << std::endl;
    for (size_t i = 0; i < v.index_cloudID.size(); ++i)
    {
      s << indent << "  index_cloudID[" << i << "]: ";
      Printer<uint32_t>::stream(s, indent + "  ", v.index_cloudID[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // LIDAR_PERCEPTION_MESSAGE_GRID_INDEX_H
