// Generated by gencpp from file iau_ros_msgs/Map.msg
// DO NOT EDIT!


#ifndef IAU_ROS_MSGS_MESSAGE_MAP_H
#define IAU_ROS_MSGS_MESSAGE_MAP_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include "../msgHeader/Lane.h"
#include "../msgHeader//PointXYA.h"

namespace iau_ros_msgs
{
template <class ContainerAllocator>
struct Map_
{
  typedef Map_<ContainerAllocator> Type;

  Map_()
    : timestamp()
    , lanenum(0)
    , road()
    , curindex(0)
    , targetindex(0)
    , curpos()
    , inconn(0)  {
    }
  Map_(const ContainerAllocator& _alloc)
    : timestamp()
    , lanenum(0)
    , road(_alloc)
    , curindex(0)
    , targetindex(0)
    , curpos(_alloc)
    , inconn(0)  {
  (void)_alloc;
    }



   typedef ros::Time _timestamp_type;
  _timestamp_type timestamp;

   typedef int32_t _lanenum_type;
  _lanenum_type lanenum;

   typedef std::vector< ::iau_ros_msgs::Lane_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::iau_ros_msgs::Lane_<ContainerAllocator> >::other >  _road_type;
  _road_type road;

   typedef int32_t _curindex_type;
  _curindex_type curindex;

   typedef int32_t _targetindex_type;
  _targetindex_type targetindex;

   typedef  ::iau_ros_msgs::PointXYA_<ContainerAllocator>  _curpos_type;
  _curpos_type curpos;

   typedef int8_t _inconn_type;
  _inconn_type inconn;





  typedef boost::shared_ptr< ::iau_ros_msgs::Map_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::iau_ros_msgs::Map_<ContainerAllocator> const> ConstPtr;

}; // struct Map_

typedef ::iau_ros_msgs::Map_<std::allocator<void> > Map;

typedef boost::shared_ptr< ::iau_ros_msgs::Map > MapPtr;
typedef boost::shared_ptr< ::iau_ros_msgs::Map const> MapConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::iau_ros_msgs::Map_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::iau_ros_msgs::Map_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace iau_ros_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'iau_ros_msgs': ['/home/z/iau_ws/src/iau_ros_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::iau_ros_msgs::Map_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::iau_ros_msgs::Map_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::iau_ros_msgs::Map_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::iau_ros_msgs::Map_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iau_ros_msgs::Map_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iau_ros_msgs::Map_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::iau_ros_msgs::Map_<ContainerAllocator> >
{
  static const char* value()
  {
    return "06181fcf446d535a7294dab98b1e1858";
  }

  static const char* value(const ::iau_ros_msgs::Map_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x06181fcf446d535aULL;
  static const uint64_t static_value2 = 0x7294dab98b1e1858ULL;
};

template<class ContainerAllocator>
struct DataType< ::iau_ros_msgs::Map_<ContainerAllocator> >
{
  static const char* value()
  {
    return "iau_ros_msgs/Map";
  }

  static const char* value(const ::iau_ros_msgs::Map_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::iau_ros_msgs::Map_<ContainerAllocator> >
{
  static const char* value()
  {
    return "time     timestamp\n\
int32    lanenum  # lane amount in road, use road.size() instead\n\
Lane[]   road\n\
int32    curindex\n\
int32    targetindex\n\
PointXYA curpos\n\
int8     inconn\n\
\n\
\n\
================================================================================\n\
MSG: iau_ros_msgs/Lane\n\
int32     num\n\
PointXYA[]  points\n\
\n\
================================================================================\n\
MSG: iau_ros_msgs/PointXYA\n\
float64 x\n\
float64 y\n\
float64 yaw  # degs\n\
";
  }

  static const char* value(const ::iau_ros_msgs::Map_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::iau_ros_msgs::Map_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.timestamp);
      stream.next(m.lanenum);
      stream.next(m.road);
      stream.next(m.curindex);
      stream.next(m.targetindex);
      stream.next(m.curpos);
      stream.next(m.inconn);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Map_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::iau_ros_msgs::Map_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::iau_ros_msgs::Map_<ContainerAllocator>& v)
  {
    s << indent << "timestamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.timestamp);
    s << indent << "lanenum: ";
    Printer<int32_t>::stream(s, indent + "  ", v.lanenum);
    s << indent << "road[]" << std::endl;
    for (size_t i = 0; i < v.road.size(); ++i)
    {
      s << indent << "  road[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::iau_ros_msgs::Lane_<ContainerAllocator> >::stream(s, indent + "    ", v.road[i]);
    }
    s << indent << "curindex: ";
    Printer<int32_t>::stream(s, indent + "  ", v.curindex);
    s << indent << "targetindex: ";
    Printer<int32_t>::stream(s, indent + "  ", v.targetindex);
    s << indent << "curpos: ";
    s << std::endl;
    Printer< ::iau_ros_msgs::PointXYA_<ContainerAllocator> >::stream(s, indent + "  ", v.curpos);
    s << indent << "inconn: ";
    Printer<int8_t>::stream(s, indent + "  ", v.inconn);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IAU_ROS_MSGS_MESSAGE_MAP_H
