// Generated by gencpp from file lidar_perception/obs2segMsg.msg
// DO NOT EDIT!


#ifndef LIDAR_PERCEPTION_MESSAGE_OBS2SEGMSG_H
#define LIDAR_PERCEPTION_MESSAGE_OBS2SEGMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <sensor_msgs/PointCloud2.h>
#include "cloud_index.h"
#include "grid_index.h"

namespace lidar_perception
{
template <class ContainerAllocator>
struct obs2segMsg_
{
  typedef obs2segMsg_<ContainerAllocator> Type;

  obs2segMsg_()
    : header()
    , grid_rows(0)
    , grid_cols(0)
    , cloud()
    , cloud_flag()
    , grid_flag()
    , cloud_gridID()
    , grid_cloudID()  {
    }
  obs2segMsg_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , grid_rows(0)
    , grid_cols(0)
    , cloud(_alloc)
    , cloud_flag(_alloc)
    , grid_flag(_alloc)
    , cloud_gridID(_alloc)
    , grid_cloudID(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint16_t _grid_rows_type;
  _grid_rows_type grid_rows;

   typedef uint16_t _grid_cols_type;
  _grid_cols_type grid_cols;

   typedef  ::sensor_msgs::PointCloud2_<ContainerAllocator>  _cloud_type;
  _cloud_type cloud;

   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _cloud_flag_type;
  _cloud_flag_type cloud_flag;

   typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _grid_flag_type;
  _grid_flag_type grid_flag;

   typedef std::vector< ::lidar_perception::cloud_index_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::lidar_perception::cloud_index_<ContainerAllocator> >::other >  _cloud_gridID_type;
  _cloud_gridID_type cloud_gridID;

   typedef std::vector< ::lidar_perception::grid_index_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::lidar_perception::grid_index_<ContainerAllocator> >::other >  _grid_cloudID_type;
  _grid_cloudID_type grid_cloudID;





  typedef boost::shared_ptr< ::lidar_perception::obs2segMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lidar_perception::obs2segMsg_<ContainerAllocator> const> ConstPtr;

}; // struct obs2segMsg_

typedef ::lidar_perception::obs2segMsg_<std::allocator<void> > obs2segMsg;

typedef boost::shared_ptr< ::lidar_perception::obs2segMsg > obs2segMsgPtr;
typedef boost::shared_ptr< ::lidar_perception::obs2segMsg const> obs2segMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lidar_perception::obs2segMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lidar_perception::obs2segMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace lidar_perception

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'lidar_perception': ['/home/jydragon/catkin_ws/src/lidar_perception/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::lidar_perception::obs2segMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lidar_perception::obs2segMsg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lidar_perception::obs2segMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lidar_perception::obs2segMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lidar_perception::obs2segMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lidar_perception::obs2segMsg_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lidar_perception::obs2segMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1f1f41f1e00b4025c03f7e3433a56e30";
  }

  static const char* value(const ::lidar_perception::obs2segMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1f1f41f1e00b4025ULL;
  static const uint64_t static_value2 = 0xc03f7e3433a56e30ULL;
};

template<class ContainerAllocator>
struct DataType< ::lidar_perception::obs2segMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lidar_perception/obs2segMsg";
  }

  static const char* value(const ::lidar_perception::obs2segMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lidar_perception::obs2segMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
uint16 grid_rows\n\
uint16 grid_cols\n\
sensor_msgs/PointCloud2 cloud\n\
int32[] cloud_flag\n\
bool[] grid_flag\n\
cloud_index[] cloud_gridID\n\
grid_index[] grid_cloudID\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: sensor_msgs/PointCloud2\n\
# This message holds a collection of N-dimensional points, which may\n\
# contain additional information such as normals, intensity, etc. The\n\
# point data is stored as a binary blob, its layout described by the\n\
# contents of the \"fields\" array.\n\
\n\
# The point cloud data may be organized 2d (image-like) or 1d\n\
# (unordered). Point clouds organized as 2d images may be produced by\n\
# camera depth sensors such as stereo or time-of-flight.\n\
\n\
# Time of sensor data acquisition, and the coordinate frame ID (for 3d\n\
# points).\n\
Header header\n\
\n\
# 2D structure of the point cloud. If the cloud is unordered, height is\n\
# 1 and width is the length of the point cloud.\n\
uint32 height\n\
uint32 width\n\
\n\
# Describes the channels and their layout in the binary data blob.\n\
PointField[] fields\n\
\n\
bool    is_bigendian # Is this data bigendian?\n\
uint32  point_step   # Length of a point in bytes\n\
uint32  row_step     # Length of a row in bytes\n\
uint8[] data         # Actual point data, size is (row_step*height)\n\
\n\
bool is_dense        # True if there are no invalid points\n\
\n\
================================================================================\n\
MSG: sensor_msgs/PointField\n\
# This message holds the description of one point entry in the\n\
# PointCloud2 message format.\n\
uint8 INT8    = 1\n\
uint8 UINT8   = 2\n\
uint8 INT16   = 3\n\
uint8 UINT16  = 4\n\
uint8 INT32   = 5\n\
uint8 UINT32  = 6\n\
uint8 FLOAT32 = 7\n\
uint8 FLOAT64 = 8\n\
\n\
string name      # Name of field\n\
uint32 offset    # Offset from start of point struct\n\
uint8  datatype  # Datatype enumeration, see above\n\
uint32 count     # How many elements in the field\n\
\n\
================================================================================\n\
MSG: lidar_perception/cloud_index\n\
uint16 row\n\
uint16 col\n\
================================================================================\n\
MSG: lidar_perception/grid_index\n\
uint16 row\n\
uint16 col\n\
uint32[] index_cloudID\n\
";
  }

  static const char* value(const ::lidar_perception::obs2segMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lidar_perception::obs2segMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.grid_rows);
      stream.next(m.grid_cols);
      stream.next(m.cloud);
      stream.next(m.cloud_flag);
      stream.next(m.grid_flag);
      stream.next(m.cloud_gridID);
      stream.next(m.grid_cloudID);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct obs2segMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lidar_perception::obs2segMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lidar_perception::obs2segMsg_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "grid_rows: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.grid_rows);
    s << indent << "grid_cols: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.grid_cols);
    s << indent << "cloud: ";
    s << std::endl;
    Printer< ::sensor_msgs::PointCloud2_<ContainerAllocator> >::stream(s, indent + "  ", v.cloud);
    s << indent << "cloud_flag[]" << std::endl;
    for (size_t i = 0; i < v.cloud_flag.size(); ++i)
    {
      s << indent << "  cloud_flag[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.cloud_flag[i]);
    }
    s << indent << "grid_flag[]" << std::endl;
    for (size_t i = 0; i < v.grid_flag.size(); ++i)
    {
      s << indent << "  grid_flag[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.grid_flag[i]);
    }
    s << indent << "cloud_gridID[]" << std::endl;
    for (size_t i = 0; i < v.cloud_gridID.size(); ++i)
    {
      s << indent << "  cloud_gridID[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::lidar_perception::cloud_index_<ContainerAllocator> >::stream(s, indent + "    ", v.cloud_gridID[i]);
    }
    s << indent << "grid_cloudID[]" << std::endl;
    for (size_t i = 0; i < v.grid_cloudID.size(); ++i)
    {
      s << indent << "  grid_cloudID[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::lidar_perception::grid_index_<ContainerAllocator> >::stream(s, indent + "    ", v.grid_cloudID[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // LIDAR_PERCEPTION_MESSAGE_OBS2SEGMSG_H
