// Generated by gencpp from file iau_ros_msgs/PointXYA.msg
// DO NOT EDIT!


#ifndef IAU_ROS_MSGS_MESSAGE_POINTXYA_H
#define IAU_ROS_MSGS_MESSAGE_POINTXYA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace iau_ros_msgs
{
template <class ContainerAllocator>
struct PointXYA_
{
  typedef PointXYA_<ContainerAllocator> Type;

  PointXYA_()
    : x(0.0)
    , y(0.0)
    , yaw(0.0)  {
    }
  PointXYA_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , yaw(0.0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _yaw_type;
  _yaw_type yaw;





  typedef boost::shared_ptr< ::iau_ros_msgs::PointXYA_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::iau_ros_msgs::PointXYA_<ContainerAllocator> const> ConstPtr;

}; // struct PointXYA_

typedef ::iau_ros_msgs::PointXYA_<std::allocator<void> > PointXYA;

typedef boost::shared_ptr< ::iau_ros_msgs::PointXYA > PointXYAPtr;
typedef boost::shared_ptr< ::iau_ros_msgs::PointXYA const> PointXYAConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::iau_ros_msgs::PointXYA_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::iau_ros_msgs::PointXYA_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace iau_ros_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'iau_ros_msgs': ['/home/z/iau_ws/src/iau_ros_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::iau_ros_msgs::PointXYA_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::iau_ros_msgs::PointXYA_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::iau_ros_msgs::PointXYA_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::iau_ros_msgs::PointXYA_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iau_ros_msgs::PointXYA_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iau_ros_msgs::PointXYA_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::iau_ros_msgs::PointXYA_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b71344c0ba01936756dc45bcd89ef437";
  }

  static const char* value(const ::iau_ros_msgs::PointXYA_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb71344c0ba019367ULL;
  static const uint64_t static_value2 = 0x56dc45bcd89ef437ULL;
};

template<class ContainerAllocator>
struct DataType< ::iau_ros_msgs::PointXYA_<ContainerAllocator> >
{
  static const char* value()
  {
    return "iau_ros_msgs/PointXYA";
  }

  static const char* value(const ::iau_ros_msgs::PointXYA_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::iau_ros_msgs::PointXYA_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x\n\
float64 y\n\
float64 yaw  # degs\n\
";
  }

  static const char* value(const ::iau_ros_msgs::PointXYA_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::iau_ros_msgs::PointXYA_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.yaw);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PointXYA_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::iau_ros_msgs::PointXYA_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::iau_ros_msgs::PointXYA_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "yaw: ";
    Printer<double>::stream(s, indent + "  ", v.yaw);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IAU_ROS_MSGS_MESSAGE_POINTXYA_H
