// Generated by gencpp from file iau_ros_msgs/ReverseLane.msg
// DO NOT EDIT!


#ifndef IAU_ROS_MSGS_MESSAGE_REVERSELANE_H
#define IAU_ROS_MSGS_MESSAGE_REVERSELANE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <iau_ros_msgs/Lane.h>

namespace iau_ros_msgs
{
template <class ContainerAllocator>
struct ReverseLane_
{
  typedef ReverseLane_<ContainerAllocator> Type;

  ReverseLane_()
    : timestamp()
    , lane()  {
    }
  ReverseLane_(const ContainerAllocator& _alloc)
    : timestamp()
    , lane(_alloc)  {
  (void)_alloc;
    }



   typedef ros::Time _timestamp_type;
  _timestamp_type timestamp;

   typedef  ::iau_ros_msgs::Lane_<ContainerAllocator>  _lane_type;
  _lane_type lane;





  typedef boost::shared_ptr< ::iau_ros_msgs::ReverseLane_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::iau_ros_msgs::ReverseLane_<ContainerAllocator> const> ConstPtr;

}; // struct ReverseLane_

typedef ::iau_ros_msgs::ReverseLane_<std::allocator<void> > ReverseLane;

typedef boost::shared_ptr< ::iau_ros_msgs::ReverseLane > ReverseLanePtr;
typedef boost::shared_ptr< ::iau_ros_msgs::ReverseLane const> ReverseLaneConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::iau_ros_msgs::ReverseLane_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::iau_ros_msgs::ReverseLane_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace iau_ros_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'iau_ros_msgs': ['/home/z/iau_ws/src/iau_ros_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::iau_ros_msgs::ReverseLane_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::iau_ros_msgs::ReverseLane_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::iau_ros_msgs::ReverseLane_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::iau_ros_msgs::ReverseLane_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iau_ros_msgs::ReverseLane_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iau_ros_msgs::ReverseLane_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::iau_ros_msgs::ReverseLane_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2055ce68fbdbc7f817b115dc7cb7a7af";
  }

  static const char* value(const ::iau_ros_msgs::ReverseLane_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2055ce68fbdbc7f8ULL;
  static const uint64_t static_value2 = 0x17b115dc7cb7a7afULL;
};

template<class ContainerAllocator>
struct DataType< ::iau_ros_msgs::ReverseLane_<ContainerAllocator> >
{
  static const char* value()
  {
    return "iau_ros_msgs/ReverseLane";
  }

  static const char* value(const ::iau_ros_msgs::ReverseLane_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::iau_ros_msgs::ReverseLane_<ContainerAllocator> >
{
  static const char* value()
  {
    return "time    timestamp\n\
Lane    lane\n\
\n\
================================================================================\n\
MSG: iau_ros_msgs/Lane\n\
int32     num\n\
PointXYA[]  points\n\
\n\
================================================================================\n\
MSG: iau_ros_msgs/PointXYA\n\
float64 x\n\
float64 y\n\
float64 yaw  # degs\n\
";
  }

  static const char* value(const ::iau_ros_msgs::ReverseLane_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::iau_ros_msgs::ReverseLane_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.timestamp);
      stream.next(m.lane);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ReverseLane_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::iau_ros_msgs::ReverseLane_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::iau_ros_msgs::ReverseLane_<ContainerAllocator>& v)
  {
    s << indent << "timestamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.timestamp);
    s << indent << "lane: ";
    s << std::endl;
    Printer< ::iau_ros_msgs::Lane_<ContainerAllocator> >::stream(s, indent + "  ", v.lane);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IAU_ROS_MSGS_MESSAGE_REVERSELANE_H
