// Generated by gencpp from file iau_ros_msgs/Scene.msg
// DO NOT EDIT!


#ifndef IAU_ROS_MSGS_MESSAGE_SCENE_H
#define IAU_ROS_MSGS_MESSAGE_SCENE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace iau_ros_msgs
{
template <class ContainerAllocator>
struct Scene_
{
  typedef Scene_<ContainerAllocator> Type;

  Scene_()
    : timestamp()
    , status(0)  {
    }
  Scene_(const ContainerAllocator& _alloc)
    : timestamp()
    , status(0)  {
  (void)_alloc;
    }



   typedef ros::Time _timestamp_type;
  _timestamp_type timestamp;

   typedef int32_t _status_type;
  _status_type status;



  enum {
    TYPE_STATUS_SLOW = 1,
    TYPE_STATUS_STOP = 2,
    TYPE_STATUS_YEILD = 4,
    TYPE_STATUS_AVOID = 8,
    TYPE_STATUS_STRAIGHT = 16,
    TYPE_STATUS_LEFT = 32,
    TYPE_STATUS_RIGHT = 64,
  };


  typedef boost::shared_ptr< ::iau_ros_msgs::Scene_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::iau_ros_msgs::Scene_<ContainerAllocator> const> ConstPtr;

}; // struct Scene_

typedef ::iau_ros_msgs::Scene_<std::allocator<void> > Scene;

typedef boost::shared_ptr< ::iau_ros_msgs::Scene > ScenePtr;
typedef boost::shared_ptr< ::iau_ros_msgs::Scene const> SceneConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::iau_ros_msgs::Scene_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::iau_ros_msgs::Scene_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace iau_ros_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'iau_ros_msgs': ['/home/z/iau_ws/src/iau_ros_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::iau_ros_msgs::Scene_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::iau_ros_msgs::Scene_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::iau_ros_msgs::Scene_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::iau_ros_msgs::Scene_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iau_ros_msgs::Scene_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iau_ros_msgs::Scene_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::iau_ros_msgs::Scene_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e131e46b2052285ab0284238f9d983a8";
  }

  static const char* value(const ::iau_ros_msgs::Scene_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe131e46b2052285aULL;
  static const uint64_t static_value2 = 0xb0284238f9d983a8ULL;
};

template<class ContainerAllocator>
struct DataType< ::iau_ros_msgs::Scene_<ContainerAllocator> >
{
  static const char* value()
  {
    return "iau_ros_msgs/Scene";
  }

  static const char* value(const ::iau_ros_msgs::Scene_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::iau_ros_msgs::Scene_<ContainerAllocator> >
{
  static const char* value()
  {
    return "time      timestamp\n\
int32     status    # 1:slow 2:stop 4: yeild 8:avoid 16:straight 32:left 64:right\n\
\n\
\n\
int32    TYPE_STATUS_SLOW       = 1\n\
int32    TYPE_STATUS_STOP       = 2\n\
int32    TYPE_STATUS_YEILD      = 4\n\
int32    TYPE_STATUS_AVOID      = 8\n\
int32    TYPE_STATUS_STRAIGHT   = 16\n\
int32    TYPE_STATUS_LEFT       = 32\n\
int32    TYPE_STATUS_RIGHT      = 64\n\
";
  }

  static const char* value(const ::iau_ros_msgs::Scene_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::iau_ros_msgs::Scene_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.timestamp);
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Scene_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::iau_ros_msgs::Scene_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::iau_ros_msgs::Scene_<ContainerAllocator>& v)
  {
    s << indent << "timestamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.timestamp);
    s << indent << "status: ";
    Printer<int32_t>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IAU_ROS_MSGS_MESSAGE_SCENE_H
