// Generated by gencpp from file iau_ros_msgs/TrafficLightResult.msg
// DO NOT EDIT!


#ifndef IAU_ROS_MSGS_MESSAGE_TRAFFICLIGHTRESULT_H
#define IAU_ROS_MSGS_MESSAGE_TRAFFICLIGHTRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace iau_ros_msgs
{
template <class ContainerAllocator>
struct TrafficLightResult_
{
  typedef TrafficLightResult_<ContainerAllocator> Type;

  TrafficLightResult_()
    : timestamp()
    , result_id(0)
    , lights_status()  {
    }
  TrafficLightResult_(const ContainerAllocator& _alloc)
    : timestamp()
    , result_id(0)
    , lights_status(_alloc)  {
  (void)_alloc;
    }



   typedef ros::Time _timestamp_type;
  _timestamp_type timestamp;

   typedef int32_t _result_id_type;
  _result_id_type result_id;

   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _lights_status_type;
  _lights_status_type lights_status;





  typedef boost::shared_ptr< ::iau_ros_msgs::TrafficLightResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::iau_ros_msgs::TrafficLightResult_<ContainerAllocator> const> ConstPtr;

}; // struct TrafficLightResult_

typedef ::iau_ros_msgs::TrafficLightResult_<std::allocator<void> > TrafficLightResult;

typedef boost::shared_ptr< ::iau_ros_msgs::TrafficLightResult > TrafficLightResultPtr;
typedef boost::shared_ptr< ::iau_ros_msgs::TrafficLightResult const> TrafficLightResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::iau_ros_msgs::TrafficLightResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::iau_ros_msgs::TrafficLightResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace iau_ros_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'iau_ros_msgs': ['/home/z/iau_ws/src/iau_ros_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::iau_ros_msgs::TrafficLightResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::iau_ros_msgs::TrafficLightResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::iau_ros_msgs::TrafficLightResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::iau_ros_msgs::TrafficLightResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iau_ros_msgs::TrafficLightResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iau_ros_msgs::TrafficLightResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::iau_ros_msgs::TrafficLightResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2cd1208b0c0ec41e65421638494f7020";
  }

  static const char* value(const ::iau_ros_msgs::TrafficLightResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2cd1208b0c0ec41eULL;
  static const uint64_t static_value2 = 0x65421638494f7020ULL;
};

template<class ContainerAllocator>
struct DataType< ::iau_ros_msgs::TrafficLightResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "iau_ros_msgs/TrafficLightResult";
  }

  static const char* value(const ::iau_ros_msgs::TrafficLightResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::iau_ros_msgs::TrafficLightResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "time      timestamp\n\
int32     result_id\n\
int32[]   lights_status\n\
";
  }

  static const char* value(const ::iau_ros_msgs::TrafficLightResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::iau_ros_msgs::TrafficLightResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.timestamp);
      stream.next(m.result_id);
      stream.next(m.lights_status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TrafficLightResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::iau_ros_msgs::TrafficLightResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::iau_ros_msgs::TrafficLightResult_<ContainerAllocator>& v)
  {
    s << indent << "timestamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.timestamp);
    s << indent << "result_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.result_id);
    s << indent << "lights_status[]" << std::endl;
    for (size_t i = 0; i < v.lights_status.size(); ++i)
    {
      s << indent << "  lights_status[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.lights_status[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // IAU_ROS_MSGS_MESSAGE_TRAFFICLIGHTRESULT_H
