// Generated by gencpp from file iau_ros_msgs/TrafficSign.msg
// DO NOT EDIT!


#ifndef IAU_ROS_MSGS_MESSAGE_TRAFFICSIGN_H
#define IAU_ROS_MSGS_MESSAGE_TRAFFICSIGN_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace iau_ros_msgs
{
template <class ContainerAllocator>
struct TrafficSign_
{
  typedef TrafficSign_<ContainerAllocator> Type;

  TrafficSign_()
    : timestamp()
    , sign_type(0)
    , sign_pos()  {
    }
  TrafficSign_(const ContainerAllocator& _alloc)
    : timestamp()
    , sign_type(0)
    , sign_pos(_alloc)  {
  (void)_alloc;
    }



   typedef ros::Time _timestamp_type;
  _timestamp_type timestamp;

   typedef int32_t _sign_type_type;
  _sign_type_type sign_type;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _sign_pos_type;
  _sign_pos_type sign_pos;





  typedef boost::shared_ptr< ::iau_ros_msgs::TrafficSign_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::iau_ros_msgs::TrafficSign_<ContainerAllocator> const> ConstPtr;

}; // struct TrafficSign_

typedef ::iau_ros_msgs::TrafficSign_<std::allocator<void> > TrafficSign;

typedef boost::shared_ptr< ::iau_ros_msgs::TrafficSign > TrafficSignPtr;
typedef boost::shared_ptr< ::iau_ros_msgs::TrafficSign const> TrafficSignConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::iau_ros_msgs::TrafficSign_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::iau_ros_msgs::TrafficSign_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace iau_ros_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'iau_ros_msgs': ['/home/z/iau_ws/src/iau_ros_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::iau_ros_msgs::TrafficSign_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::iau_ros_msgs::TrafficSign_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::iau_ros_msgs::TrafficSign_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::iau_ros_msgs::TrafficSign_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iau_ros_msgs::TrafficSign_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iau_ros_msgs::TrafficSign_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::iau_ros_msgs::TrafficSign_<ContainerAllocator> >
{
  static const char* value()
  {
    return "98340579549a877faf9dbd05b3a55869";
  }

  static const char* value(const ::iau_ros_msgs::TrafficSign_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x98340579549a877fULL;
  static const uint64_t static_value2 = 0xaf9dbd05b3a55869ULL;
};

template<class ContainerAllocator>
struct DataType< ::iau_ros_msgs::TrafficSign_<ContainerAllocator> >
{
  static const char* value()
  {
    return "iau_ros_msgs/TrafficSign";
  }

  static const char* value(const ::iau_ros_msgs::TrafficSign_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::iau_ros_msgs::TrafficSign_<ContainerAllocator> >
{
  static const char* value()
  {
    return "time      timestamp\n\
int32       sign_type\n\
float64[]   sign_pos\n\
";
  }

  static const char* value(const ::iau_ros_msgs::TrafficSign_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::iau_ros_msgs::TrafficSign_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.timestamp);
      stream.next(m.sign_type);
      stream.next(m.sign_pos);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TrafficSign_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::iau_ros_msgs::TrafficSign_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::iau_ros_msgs::TrafficSign_<ContainerAllocator>& v)
  {
    s << indent << "timestamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.timestamp);
    s << indent << "sign_type: ";
    Printer<int32_t>::stream(s, indent + "  ", v.sign_type);
    s << indent << "sign_pos[]" << std::endl;
    for (size_t i = 0; i < v.sign_pos.size(); ++i)
    {
      s << indent << "  sign_pos[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.sign_pos[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // IAU_ROS_MSGS_MESSAGE_TRAFFICSIGN_H
