// Generated by gencpp from file iau_ros_msgs/VehicleLight.msg
// DO NOT EDIT!


#ifndef IAU_ROS_MSGS_MESSAGE_VEHICLELIGHT_H
#define IAU_ROS_MSGS_MESSAGE_VEHICLELIGHT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace iau_ros_msgs
{
template <class ContainerAllocator>
struct VehicleLight_
{
  typedef VehicleLight_<ContainerAllocator> Type;

  VehicleLight_()
    : light(0)  {
    }
  VehicleLight_(const ContainerAllocator& _alloc)
    : light(0)  {
  (void)_alloc;
    }



   typedef int8_t _light_type;
  _light_type light;





  typedef boost::shared_ptr< ::iau_ros_msgs::VehicleLight_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::iau_ros_msgs::VehicleLight_<ContainerAllocator> const> ConstPtr;

}; // struct VehicleLight_

typedef ::iau_ros_msgs::VehicleLight_<std::allocator<void> > VehicleLight;

typedef boost::shared_ptr< ::iau_ros_msgs::VehicleLight > VehicleLightPtr;
typedef boost::shared_ptr< ::iau_ros_msgs::VehicleLight const> VehicleLightConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::iau_ros_msgs::VehicleLight_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::iau_ros_msgs::VehicleLight_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace iau_ros_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'iau_ros_msgs': ['/home/z/iau_ws/src/iau_ros_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::iau_ros_msgs::VehicleLight_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::iau_ros_msgs::VehicleLight_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::iau_ros_msgs::VehicleLight_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::iau_ros_msgs::VehicleLight_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iau_ros_msgs::VehicleLight_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iau_ros_msgs::VehicleLight_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::iau_ros_msgs::VehicleLight_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0fcb06f7137d03943c1de834246695ad";
  }

  static const char* value(const ::iau_ros_msgs::VehicleLight_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0fcb06f7137d0394ULL;
  static const uint64_t static_value2 = 0x3c1de834246695adULL;
};

template<class ContainerAllocator>
struct DataType< ::iau_ros_msgs::VehicleLight_<ContainerAllocator> >
{
  static const char* value()
  {
    return "iau_ros_msgs/VehicleLight";
  }

  static const char* value(const ::iau_ros_msgs::VehicleLight_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::iau_ros_msgs::VehicleLight_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# b'xxxxxxx1 low_beam\n\
# b'xxxxxx1x high_beam\n\
# b'xxxxx1xx pos_light\n\
# b'xxxx1xxx left_turn_light\n\
# b'xxx1xxxx right_turn_light\n\
# b'xx1xxxxx brake_light\n\
int8 light\n\
";
  }

  static const char* value(const ::iau_ros_msgs::VehicleLight_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::iau_ros_msgs::VehicleLight_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.light);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VehicleLight_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::iau_ros_msgs::VehicleLight_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::iau_ros_msgs::VehicleLight_<ContainerAllocator>& v)
  {
    s << indent << "light: ";
    Printer<int8_t>::stream(s, indent + "  ", v.light);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IAU_ROS_MSGS_MESSAGE_VEHICLELIGHT_H
