// Generated by gencpp from file iau_ros_msgs/VehicleStatus.msg
// DO NOT EDIT!


#ifndef IAU_ROS_MSGS_MESSAGE_VEHICLESTATUS_H
#define IAU_ROS_MSGS_MESSAGE_VEHICLESTATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace iau_ros_msgs
{
template <class ContainerAllocator>
struct VehicleStatus_
{
  typedef VehicleStatus_<ContainerAllocator> Type;

  VehicleStatus_()
    : timestamp()
    , steerAngle(0.0)
    , vehicleSpeed(0.0)
    , gear(0)
    , controlStatus(0)  {
    }
  VehicleStatus_(const ContainerAllocator& _alloc)
    : timestamp()
    , steerAngle(0.0)
    , vehicleSpeed(0.0)
    , gear(0)
    , controlStatus(0)  {
  (void)_alloc;
    }



   typedef ros::Time _timestamp_type;
  _timestamp_type timestamp;

   typedef double _steerAngle_type;
  _steerAngle_type steerAngle;

   typedef double _vehicleSpeed_type;
  _vehicleSpeed_type vehicleSpeed;

   typedef int8_t _gear_type;
  _gear_type gear;

   typedef int8_t _controlStatus_type;
  _controlStatus_type controlStatus;





  typedef boost::shared_ptr< ::iau_ros_msgs::VehicleStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::iau_ros_msgs::VehicleStatus_<ContainerAllocator> const> ConstPtr;

}; // struct VehicleStatus_

typedef ::iau_ros_msgs::VehicleStatus_<std::allocator<void> > VehicleStatus;

typedef boost::shared_ptr< ::iau_ros_msgs::VehicleStatus > VehicleStatusPtr;
typedef boost::shared_ptr< ::iau_ros_msgs::VehicleStatus const> VehicleStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::iau_ros_msgs::VehicleStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::iau_ros_msgs::VehicleStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace iau_ros_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'iau_ros_msgs': ['/home/z/iau_ws/src/iau_ros_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::iau_ros_msgs::VehicleStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::iau_ros_msgs::VehicleStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::iau_ros_msgs::VehicleStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::iau_ros_msgs::VehicleStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iau_ros_msgs::VehicleStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iau_ros_msgs::VehicleStatus_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::iau_ros_msgs::VehicleStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1109056be4f40a095eaa3ee1757e890e";
  }

  static const char* value(const ::iau_ros_msgs::VehicleStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1109056be4f40a09ULL;
  static const uint64_t static_value2 = 0x5eaa3ee1757e890eULL;
};

template<class ContainerAllocator>
struct DataType< ::iau_ros_msgs::VehicleStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "iau_ros_msgs/VehicleStatus";
  }

  static const char* value(const ::iau_ros_msgs::VehicleStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::iau_ros_msgs::VehicleStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "time timestamp\n\
float64 steerAngle\n\
float64 vehicleSpeed\n\
int8 gear\n\
int8 controlStatus\n\
";
  }

  static const char* value(const ::iau_ros_msgs::VehicleStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::iau_ros_msgs::VehicleStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.timestamp);
      stream.next(m.steerAngle);
      stream.next(m.vehicleSpeed);
      stream.next(m.gear);
      stream.next(m.controlStatus);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VehicleStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::iau_ros_msgs::VehicleStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::iau_ros_msgs::VehicleStatus_<ContainerAllocator>& v)
  {
    s << indent << "timestamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.timestamp);
    s << indent << "steerAngle: ";
    Printer<double>::stream(s, indent + "  ", v.steerAngle);
    s << indent << "vehicleSpeed: ";
    Printer<double>::stream(s, indent + "  ", v.vehicleSpeed);
    s << indent << "gear: ";
    Printer<int8_t>::stream(s, indent + "  ", v.gear);
    s << indent << "controlStatus: ";
    Printer<int8_t>::stream(s, indent + "  ", v.controlStatus);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IAU_ROS_MSGS_MESSAGE_VEHICLESTATUS_H
