// Generated by gencpp from file iau_ros_msgs/Velocity.msg
// DO NOT EDIT!


#ifndef IAU_ROS_MSGS_MESSAGE_VELOCITY_H
#define IAU_ROS_MSGS_MESSAGE_VELOCITY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace iau_ros_msgs
{
template <class ContainerAllocator>
struct Velocity_
{
  typedef Velocity_<ContainerAllocator> Type;

  Velocity_()
    : timestamp()
    , velocity(0.0)  {
    }
  Velocity_(const ContainerAllocator& _alloc)
    : timestamp()
    , velocity(0.0)  {
  (void)_alloc;
    }



   typedef ros::Time _timestamp_type;
  _timestamp_type timestamp;

   typedef double _velocity_type;
  _velocity_type velocity;





  typedef boost::shared_ptr< ::iau_ros_msgs::Velocity_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::iau_ros_msgs::Velocity_<ContainerAllocator> const> ConstPtr;

}; // struct Velocity_

typedef ::iau_ros_msgs::Velocity_<std::allocator<void> > Velocity;

typedef boost::shared_ptr< ::iau_ros_msgs::Velocity > VelocityPtr;
typedef boost::shared_ptr< ::iau_ros_msgs::Velocity const> VelocityConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::iau_ros_msgs::Velocity_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::iau_ros_msgs::Velocity_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace iau_ros_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'iau_ros_msgs': ['/home/z/iau_ws/src/iau_ros_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::iau_ros_msgs::Velocity_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::iau_ros_msgs::Velocity_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::iau_ros_msgs::Velocity_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::iau_ros_msgs::Velocity_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iau_ros_msgs::Velocity_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iau_ros_msgs::Velocity_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::iau_ros_msgs::Velocity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2904c8987abb6a848ec62c8896d4abb7";
  }

  static const char* value(const ::iau_ros_msgs::Velocity_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2904c8987abb6a84ULL;
  static const uint64_t static_value2 = 0x8ec62c8896d4abb7ULL;
};

template<class ContainerAllocator>
struct DataType< ::iau_ros_msgs::Velocity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "iau_ros_msgs/Velocity";
  }

  static const char* value(const ::iau_ros_msgs::Velocity_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::iau_ros_msgs::Velocity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "time    timestamp\n\
float64 velocity\n\
";
  }

  static const char* value(const ::iau_ros_msgs::Velocity_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::iau_ros_msgs::Velocity_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.timestamp);
      stream.next(m.velocity);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Velocity_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::iau_ros_msgs::Velocity_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::iau_ros_msgs::Velocity_<ContainerAllocator>& v)
  {
    s << indent << "timestamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.timestamp);
    s << indent << "velocity: ";
    Printer<double>::stream(s, indent + "  ", v.velocity);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IAU_ROS_MSGS_MESSAGE_VELOCITY_H
