// Generated by gencpp from file iau_ros_msgs/VisionLane.msg
// DO NOT EDIT!


#ifndef IAU_ROS_MSGS_MESSAGE_VISIONLANE_H
#define IAU_ROS_MSGS_MESSAGE_VISIONLANE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <iau_ros_msgs/PointXYA.h>
#include <iau_ros_msgs/PointXYA.h>

namespace iau_ros_msgs
{
template <class ContainerAllocator>
struct VisionLane_
{
  typedef VisionLane_<ContainerAllocator> Type;

  VisionLane_()
    : timestamp()
    , MidPointNum(0)
    , LanePointNum(0)
    , MidPoints()
    , LanePoints()  {
    }
  VisionLane_(const ContainerAllocator& _alloc)
    : timestamp()
    , MidPointNum(0)
    , LanePointNum(0)
    , MidPoints(_alloc)
    , LanePoints(_alloc)  {
  (void)_alloc;
    }



   typedef ros::Time _timestamp_type;
  _timestamp_type timestamp;

   typedef int32_t _MidPointNum_type;
  _MidPointNum_type MidPointNum;

   typedef int32_t _LanePointNum_type;
  _LanePointNum_type LanePointNum;

   typedef std::vector< ::iau_ros_msgs::PointXYA_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::iau_ros_msgs::PointXYA_<ContainerAllocator> >::other >  _MidPoints_type;
  _MidPoints_type MidPoints;

   typedef std::vector< ::iau_ros_msgs::PointXYA_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::iau_ros_msgs::PointXYA_<ContainerAllocator> >::other >  _LanePoints_type;
  _LanePoints_type LanePoints;





  typedef boost::shared_ptr< ::iau_ros_msgs::VisionLane_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::iau_ros_msgs::VisionLane_<ContainerAllocator> const> ConstPtr;

}; // struct VisionLane_

typedef ::iau_ros_msgs::VisionLane_<std::allocator<void> > VisionLane;

typedef boost::shared_ptr< ::iau_ros_msgs::VisionLane > VisionLanePtr;
typedef boost::shared_ptr< ::iau_ros_msgs::VisionLane const> VisionLaneConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::iau_ros_msgs::VisionLane_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::iau_ros_msgs::VisionLane_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace iau_ros_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'iau_ros_msgs': ['/home/z/iau_ws/src/iau_ros_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::iau_ros_msgs::VisionLane_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::iau_ros_msgs::VisionLane_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::iau_ros_msgs::VisionLane_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::iau_ros_msgs::VisionLane_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iau_ros_msgs::VisionLane_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iau_ros_msgs::VisionLane_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::iau_ros_msgs::VisionLane_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c6f2e95e3b3faed89c6b820f6a977282";
  }

  static const char* value(const ::iau_ros_msgs::VisionLane_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc6f2e95e3b3faed8ULL;
  static const uint64_t static_value2 = 0x9c6b820f6a977282ULL;
};

template<class ContainerAllocator>
struct DataType< ::iau_ros_msgs::VisionLane_<ContainerAllocator> >
{
  static const char* value()
  {
    return "iau_ros_msgs/VisionLane";
  }

  static const char* value(const ::iau_ros_msgs::VisionLane_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::iau_ros_msgs::VisionLane_<ContainerAllocator> >
{
  static const char* value()
  {
    return "time      timestamp\n\
int32     MidPointNum   # 中线点集数量\n\
int32     LanePointNum  # 车道线点集数量\n\
PointXYA[]  MidPoints   # 中线点集\n\
PointXYA[]  LanePoints  # 车道线点集\n\
================================================================================\n\
MSG: iau_ros_msgs/PointXYA\n\
float64 x\n\
float64 y\n\
float64 yaw  # degs\n\
";
  }

  static const char* value(const ::iau_ros_msgs::VisionLane_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::iau_ros_msgs::VisionLane_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.timestamp);
      stream.next(m.MidPointNum);
      stream.next(m.LanePointNum);
      stream.next(m.MidPoints);
      stream.next(m.LanePoints);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VisionLane_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::iau_ros_msgs::VisionLane_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::iau_ros_msgs::VisionLane_<ContainerAllocator>& v)
  {
    s << indent << "timestamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.timestamp);
    s << indent << "MidPointNum: ";
    Printer<int32_t>::stream(s, indent + "  ", v.MidPointNum);
    s << indent << "LanePointNum: ";
    Printer<int32_t>::stream(s, indent + "  ", v.LanePointNum);
    s << indent << "MidPoints[]" << std::endl;
    for (size_t i = 0; i < v.MidPoints.size(); ++i)
    {
      s << indent << "  MidPoints[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::iau_ros_msgs::PointXYA_<ContainerAllocator> >::stream(s, indent + "    ", v.MidPoints[i]);
    }
    s << indent << "LanePoints[]" << std::endl;
    for (size_t i = 0; i < v.LanePoints.size(); ++i)
    {
      s << indent << "  LanePoints[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::iau_ros_msgs::PointXYA_<ContainerAllocator> >::stream(s, indent + "    ", v.LanePoints[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // IAU_ROS_MSGS_MESSAGE_VISIONLANE_H
